### ISSUE TITLE
DLL Importing

### ISSUE THREAD

**Issue by mateusdnc** [D4rkTT/Redragon-Audio-Visualizer#2]
Hi, I really liked your project and I'm trying to analyze it to understand how it works, but I'm having problems importing Redragon RGB SDK, where should it be placed? I'm sorry, I'm still learning C# and I still don't have any experience.

**Comment by D4rkTT** [comment]
look at sdk docs.
https://github.com/D4rkTT/Redragon-RGB-SDK
