### ISSUE TITLE
 addition of the redragon kala

### ISSUE THREAD

**Issue by MrAntunes09** [D4rkTT/Redragon-Audio-Visualizer#5]
any chance of the redragon kala being added? if yes, do you intend to add? and thanks for the great project and greetings from brazil
(if the right place to comment is not here, I'm sorry, I'm new to gifthub)

**Comment by D4rkTT** [comment]
Sadly i must have to mouse to reversing its software and i don't have redragon kala sadly 😢

**Comment by MrAntunes09** [comment]
Whoa, what a pity, but thank you very much


Em dom., 21 de fev. de 2021 às 02:21, DarkT <notifications@github.com>
escreveu:
