### ISSUE TITLE
Mouse doesnt flash to audio, just has a random dim flash when audio is on

### ISSUE THREAD

**Issue by BlueZarth** [D4rkTT/Redragon-Audio-Visualizer#6]

**Comment by D4rkTT** [comment]
Do u mean u have a bug? If so u can upload a video of bug.
Or u just saying that the app is fake? If so the app is open-sourced u can check the source 🤫

**Comment by BlueZarth** [comment]
Nah, im not saying its fake, just a bug i think. either that or me messing up instalation, sorry for the confusion

**Comment by BlueZarth** [comment]
Sorry about the late response aswell, I didn't get email.  But yeah all that happens is the lights on the mouse turn off and blink every once in a while. Im pretty sure its a software issue on my end though
